# Generated by Django 3.0.7 on 2020-12-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=500)),
                ('question2', models.CharField(max_length=500)),
                ('question3', models.CharField(max_length=500)),
                ('question4', models.CharField(max_length=500)),
                ('question5', models.CharField(max_length=500)),
                ('question6', models.CharField(max_length=500)),
                ('question7', models.CharField(max_length=500)),
                ('question8', models.CharField(max_length=500)),
                ('question9', models.CharField(max_length=500)),
                ('question10', models.CharField(max_length=500)),
                ('question11', models.CharField(max_length=500)),
                ('question12', models.CharField(max_length=500)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scat.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('answer1', models.CharField(blank=True, max_length=500)),
                ('answer2', models.CharField(blank=True, max_length=500)),
                ('answer3', models.CharField(blank=True, max_length=500)),
                ('answer4', models.CharField(blank=True, max_length=500)),
                ('answer5', models.CharField(blank=True, max_length=500)),
                ('answer6', models.CharField(blank=True, max_length=500)),
                ('answer7', models.CharField(blank=True, max_length=500)),
                ('answer8', models.CharField(blank=True, max_length=500)),
                ('answer9', models.CharField(blank=True, max_length=500)),
                ('answer10', models.CharField(blank=True, max_length=500)),
                ('answer11', models.CharField(blank=True, max_length=500)),
                ('answer12', models.CharField(blank=True, max_length=500)),
                ('questions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scat.Questions')),
            ],
        ),
    ]
