# Generated by Django 3.0.7 on 2020-12-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('game_name',), 'verbose_name': 'game', 'verbose_name_plural': 'game'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AddField(
            model_name='questions',
            name='question_set',
            field=models.IntegerField(default=0),
        ),
    ]
